/* Generated By:JavaCC: Do not edit this line. Grammar2TreeConstants.java Version 4.1d1 */
public interface Grammar2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTENTIER = 1;
  public int JJTTEXTE = 2;
  public int JJTTEXTE_EP = 3;
  public int JJTBOOLEEN = 4;
  public int JJTTYPE_VAR = 5;
  public int JJTTABLEAU = 6;
  public int JJTNOM = 7;
  public int JJTNOM_EP = 8;
  public int JJTNOM_VAR = 9;
  public int JJTDECL_VAR = 10;
  public int JJTCONTENU_VAR = 11;
  public int JJTINST_VAR = 12;
  public int JJTCALCUL = 13;
  public int JJTSOMME = 14;
  public int JJTPRODUIT = 15;
  public int JJTEXPRESSION_UNAIRE = 16;
  public int JJTOPERATEUR_ARITH = 17;
  public int JJTOPERATEUR_LOGIQUE = 18;
  public int JJTOPERATEUR_EGAL = 19;
  public int JJTOPERATEUR_RELATIF = 20;


  public String[] jjtNodeName = {
    "Start",
    "ENTIER",
    "TEXTE",
    "TEXTE_EP",
    "BOOLEEN",
    "TYPE_VAR",
    "TABLEAU",
    "NOM",
    "NOM_EP",
    "NOM_VAR",
    "DECL_VAR",
    "CONTENU_VAR",
    "INST_VAR",
    "CALCUL",
    "SOMME",
    "PRODUIT",
    "EXPRESSION_UNAIRE",
    "OPERATEUR_ARITH",
    "OPERATEUR_LOGIQUE",
    "OPERATEUR_EGAL",
    "OPERATEUR_RELATIF",
  };
}
/* JavaCC - OriginalChecksum=17a3837b9baf626f842fe77c596ea780 (do not edit this line) */
