/* Generated By:JavaCC: Do not edit this line. Grammar2TreeConstants.java Version 7.0.4 */
public interface Grammar2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTENTIER = 1;
  public int JJTCORPS_VAR = 2;
  public int JJTTYPE_VAR = 3;
  public int JJTTABLEAU = 4;
  public int JJTNOM_VAR = 5;
  public int JJTDECL_VAR = 6;
  public int JJTDECL_CONST = 7;
  public int JJTCONTENU_VAR = 8;
  public int JJTINST_VAR = 9;
  public int JJTCORPS_METH = 10;
  public int JJTDECL_FONC = 11;
  public int JJTDECL_PROC = 12;
  public int JJTDECL_METH = 13;
  public int JJTDECL_PARAMS = 14;
  public int JJTAPPEL_METH = 15;
  public int JJTPARAMS = 16;
  public int JJTPARAM_VAL = 17;
  public int JJTAPPEL = 18;
  public int JJTEXPRESSION_UNAIRE = 19;
  public int JJTCALCUL = 20;
  public int JJTMULTIPLICATION = 21;
  public int JJTEXPRESSION_UNAIRE_BOOL = 22;
  public int JJTCALCUL_BOOLEEN = 23;
  public int JJTEXPRESSION_ET = 24;
  public int JJTCOMPARAISON = 25;
  public int JJTCOMP_ARITH = 26;
  public int JJTCOMP_LOGIQUE = 27;
  public int JJTCODE = 28;
  public int JJTSI = 29;
  public int JJTBOUCLE = 30;
  public int JJTPOUR = 31;
  public int JJTTANTQUE = 32;
  public int JJTOPERATEUR_EGAL = 33;
  public int JJTOPERATEUR_RELATIF = 34;
  public int JJTBLOC_VAR = 35;
  public int JJTBLOC_METH = 36;
  public int JJTMAIN = 37;
  public int JJTALGORITHME = 38;


  public String[] jjtNodeName = {
    "Start",
    "ENTIER",
    "CORPS_VAR",
    "TYPE_VAR",
    "TABLEAU",
    "NOM_VAR",
    "DECL_VAR",
    "DECL_CONST",
    "CONTENU_VAR",
    "INST_VAR",
    "CORPS_METH",
    "DECL_FONC",
    "DECL_PROC",
    "DECL_METH",
    "DECL_PARAMS",
    "APPEL_METH",
    "PARAMS",
    "PARAM_VAL",
    "APPEL",
    "EXPRESSION_UNAIRE",
    "CALCUL",
    "MULTIPLICATION",
    "EXPRESSION_UNAIRE_BOOL",
    "CALCUL_BOOLEEN",
    "EXPRESSION_ET",
    "COMPARAISON",
    "COMP_ARITH",
    "COMP_LOGIQUE",
    "CODE",
    "SI",
    "BOUCLE",
    "POUR",
    "TANTQUE",
    "OPERATEUR_EGAL",
    "OPERATEUR_RELATIF",
    "BLOC_VAR",
    "BLOC_METH",
    "MAIN",
    "ALGORITHME",
  };
}
/* JavaCC - OriginalChecksum=90d1a3ce25605192098db04b4f39017c (do not edit this line) */
