/* Generated By:JJTree&JavaCC: Do not edit this line. Grammar2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Grammar2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAJUSCULE = 4;
  /** RegularExpression Id. */
  int MINUSCULE = 5;
  /** RegularExpression Id. */
  int NOMBRE_NN = 6;
  /** RegularExpression Id. */
  int ZERO = 7;
  /** RegularExpression Id. */
  int REEL = 8;
  /** RegularExpression Id. */
  int ASSIGNATION = 9;
  /** RegularExpression Id. */
  int NOM = 10;
  /** RegularExpression Id. */
  int TEXTE = 11;
  /** RegularExpression Id. */
  int BOOLEEN = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<MAJUSCULE>",
    "<MINUSCULE>",
    "<NOMBRE_NN>",
    "<ZERO>",
    "<REEL>",
    "\"<-\"",
    "<NOM>",
    "<TEXTE>",
    "<BOOLEEN>",
    "\";\"",
    "\"ENTIER\"",
    "\"REEL\"",
    "\"TEXTE\"",
    "\"BOOLEEN\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"CONST \"",
    "\"retourne \"",
    "\"FinFonction\"",
    "\"FinProcedure\"",
    "\"Fonction \"",
    "\" \"",
    "\"Procedure \"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"NON \"",
    "\" OU \"",
    "\" ET \"",
    "\"Si \"",
    "\"Sinon \"",
    "\"FinSi\"",
    "\"Pour \"",
    "\"FinPour\"",
    "\"TantQue \"",
    "\"FinTantQue\"",
    "\"==\"",
    "\"!==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"Var\"",
    "\"FinVar\"",
    "\"Meth\"",
    "\"FinMeth\"",
    "\"Debut\"",
    "\"Fin\"",
    "\"Algo \"",
  };

}
