/* Generated By:JJTree&JavaCC: Do not edit this line. Grammar2Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Grammar2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAJUSCULE = 3;
  /** RegularExpression Id. */
  int MINUSCULE = 4;
  /** RegularExpression Id. */
  int NOMBRE_NN = 5;
  /** RegularExpression Id. */
  int ZERO = 6;
  /** RegularExpression Id. */
  int REEL = 7;
  /** RegularExpression Id. */
  int ASSIGNATION = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "<MAJUSCULE>",
    "<MINUSCULE>",
    "<NOMBRE_NN>",
    "<ZERO>",
    "<REEL>",
    "\"<-\"",
    "\";\"",
    "\"\\\"\"",
    "\"_\"",
    "\"VRAI\"",
    "\"FAUX\"",
    "\"ENTIER\"",
    "\"REEL\"",
    "\"TEXTE\"",
    "\"BOOLEEN\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\" OU \"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\" ET \"",
    "\"NON \"",
    "\"(\"",
    "\")\"",
    "\"ET\"",
    "\"OU\"",
    "\"NON\"",
    "\"==\"",
    "\"!==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
  };

}
