/* Generated By:JJTree&JavaCC: Do not edit this line. Grammar2Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Grammar2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAJUSCULE = 2;
  /** RegularExpression Id. */
  int MINUSCULE = 3;
  /** RegularExpression Id. */
  int NOMBRE_NN = 4;
  /** RegularExpression Id. */
  int ZERO = 5;
  /** RegularExpression Id. */
  int REEL = 6;
  /** RegularExpression Id. */
  int ESPACE = 7;
  /** RegularExpression Id. */
  int ASSIGNATION = 8;
  /** RegularExpression Id. */
  int NOM = 9;
  /** RegularExpression Id. */
  int TEXTE = 10;
  /** RegularExpression Id. */
  int BOOLEEN = 11;
  /** RegularExpression Id. */
  int CR = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "<MAJUSCULE>",
    "<MINUSCULE>",
    "<NOMBRE_NN>",
    "<ZERO>",
    "<REEL>",
    "<ESPACE>",
    "<ASSIGNATION>",
    "<NOM>",
    "<TEXTE>",
    "<BOOLEEN>",
    "<CR>",
    "\"-\"",
    "\"ENTIER\"",
    "\"REEL\"",
    "\"TEXTE\"",
    "\"BOOLEEN\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"CONST\"",
    "\"Retourne\"",
    "\"FinFonction\"",
    "\"FinProcedure\"",
    "\"Fonction\"",
    "\"Procedure\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"NON\"",
    "\"OU\"",
    "\"ET\"",
    "\"Si\"",
    "\"Sinon\"",
    "\"FinSi\"",
    "\"Pour\"",
    "\";\"",
    "\"FinPour\"",
    "\"TantQue\"",
    "\"FinTantQue\"",
    "\"==\"",
    "\"!==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"Var\"",
    "\"FinVar\"",
    "\"Meth\"",
    "\"FinMeth\"",
    "\"Debut\"",
    "\"Fin\"",
    "\"Algo\"",
  };

}
